### ISSUE TITLE
I you do not unite with graphql-spring-boot

### ISSUE THREAD

**Issue by raderio** [merapar/spring-boot-starter-graphql#23]
https://github.com/graphql-java/graphql-spring-boot

**Comment by janfockaert** [comment]
The two project different from implementation, what is your proposal?

**Comment by raderio** [comment]
To unite to make one team and have one good implementation

**Comment by janfockaert** [comment]
What is your idea/proposal for bringing the two projects together? In the past I looked into this project, but felt really complicated and out-dated. What is changed/improved last month(s) on this?

For my understanding, can you describe yourself a bit better and what your role is within the project, so I have an idea.

Thanks

**Comment by MartinX3** [comment]
I want to start a new project and was sad to see, that there is no official spring-boot-graphQL.

So, I found this and the mentioned project, which both use  "graphql-java", but the other one is from the same project team, which are developing "graphql-java", so I think, their project is working better with "graphql-java".

But I want to ask the developer of this spring-boot addon, where are the differents, which one is better?

PS:
Both projects are actively maintained.

**Comment by martin-g** [comment]
Looking https://github.com/graphql-java/graphql-spring-boot/commits/master most of the improvements are library updates and README. I.e. not much!

In my experience this project is much simpler and easier to use than https://github.com/graphql-java/graphql-spring-boot !

**Comment by MartinX3** [comment]
Both projects has many stars and watches, but this project has less forks and less contributors.

And if most of the improvements are library updates, that could mean, that the project is better, because there is nothing more to implement.

But I take a deeper look on both projects.

By the way: thank you for the fast response. :)

**Comment by janfockaert** [comment]
Thanks for the interests. 

We are actively maintaining and using this project it's listed in maven central, you can find the badge on the main page. Only for the development version you need to list a separate repository.

Please take a look at both projects and let us know the pros and cons.

Thanks

**Comment by MartinX3** [comment]
I looked into both sample applications.
The other project looks way more low level, than this one.
That could be caused, because they forked an already existing project instead of making a new one without old code.

In my opinion, this project is easier to use and a good example why rebuilding a house is better, than repairing and changing parts inside it.

**Comment by janfockaert** [comment]
That's a good one :)

**Comment by raderio** [comment]
The other side is interested to discuss about how to integrate the two projects
https://github.com/graphql-java/graphql-spring-boot/issues/25#issuecomment-324675555
